# General settings
general:
  site_name: 'hcxp'
  subtitle: 'hardcore punk events directory'

auth:
  # Settings specific for hcxp sign-ins
  hcxp:
    enabled: false

# Synchronization settings
sync:
  # Enable/disable synchronization
  enabled: true